### ISSUE TITLE
Pressing the Roll Key causes the player to roll while in the Inventory Screen, but not other GUIs

### ISSUE THREAD

**Issue by GekidoLukas** [ZsoltMolnarrr/Rolling#10]
**Minecraft version** - 1.18.2
**Mod loader** - Forge 
**Mod version** - 1.0.5 
**I am using the latest version available** - Yes

**Describe the bug**
When in the inventory, the player can still roll. This is an issue, because the **R** key is also used by jei etc. Changing it to a different button may also be an issue. It would be nice to have a config option to turn that off at least.

**To Reproduce**
1. Open the inventory
2. Press **R**
3. You roll

**Expected behavior**
Rolling being disabled while being in the inventory

**Comment by ZsoltMolnarrr** [comment]
Hey!
Thank you for the report!

**Comment by ZsoltMolnarrr** [comment]
This looks like a forge specific problem. It effects 1.19.X version too.

Forge is a major pain in the back...
