### ISSUE TITLE
Crash on launch 

### ISSUE THREAD

**Issue by GoldenDarius** [ZsoltMolnarrr/Rolling#11]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - 1.0.7
**I am using the latest version available** - Yes

**Describe the bug**
Once I added the mod to my modpack and tried to start the modpack, it unexpectedly crashed. I have the latest versions of the dependencies, and I cannot figure out why this happens. Here's the crash report.

[crash-2022-10-07_17.10.13-fml.txt](https://github.com/ZsoltMolnarrr/CombatRoll/files/9735123/crash-2022-10-07_17.10.13-fml.txt)

**Comment by ZsoltMolnarrr** [comment]
Looks like the Cloth-Config based configuration is failing to load.
Maybe something is interfering with it.
I cannot reproduce the issue. :(

**Comment by GoldenDarius** [comment]
I'm going to try and check if something is wrong with cloth then

**Comment by GoldenDarius** [comment]
@ZsoltMolnarrr I have found the issue, it was simply Forge not being updated. I migrated to the latest version and it is all fixed.

**Comment by ZsoltMolnarrr** [comment]
Thank you for the feedback!
