### ISSUE TITLE
[Bug report] combatroll:count 0 allows one roll

### ISSUE THREAD

**Issue by e3valdas** [ZsoltMolnarrr/Rolling#14]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric 0.14.10
**Mod version** - 1.0.8
**I am using the latest version available** - yes.

**Describe the bug**
Setting attribute combatroll:count to 0 is the same as setting it to 1 (default).

**To Reproduce**
1. Run command /attribute @s combatroll:count base set 0
2. Attempt to roll.

**Expected behavior**
Doing this should take away player's ability to roll.

**Comment by ZsoltMolnarrr** [comment]
Interesting find, I will investigate whenever I have time.

**Comment by ZsoltMolnarrr** [comment]
public static final EntityAttribute COUNT = (new ClampedEntityAttribute("attribute.name.combat_roll." + countName, 1, 1, 20.0)).setTracked(true);


(min = 1)
