### ISSUE TITLE
[Feature request] Enchantment tweaks

### ISSUE THREAD

**Issue by e3valdas** [ZsoltMolnarrr/Rolling#15]
**I read project readme, checked client side and server side configurations, and no such feature exists**
Yes.

**Describe the solution you'd like**
1. Add an ability to disable enchantments in the configuration. Even better if there's an option to choose which enchantments to keep.
2. Combine Acrobat's Shirt and Acrobat's Pants into one enchantment Acrobat that can be applied to both chestplate and leggings. Having two enchantments with the same functionality is redundant.
3. Rename Multi-Roll to Multiroll for parity with vanilla enchantment Multishot.

**Comment by ZsoltMolnarrr** [comment]
1. Enchantments can be disabled by increasing their base cost to a high value (such as 10000).
2. Acrobats Shirt and Pants can only be cross applied in Creative mode, not in survival mode.
3. Multi roll was named after MCD counterpart https://minecraft.fandom.com/wiki/Minecraft_Dungeons:Multi-Roll
