### ISSUE TITLE
cloth config window in mods menu crashes 1.18.2

### ISSUE THREAD

**Issue by Monster-Zer0** [ZsoltMolnarrr/Rolling#16]
**Minecraft version** - 1.18.2
**Mod loader** - fabric 0.14.9
**Mod version** 1.0.8
**I am using the latest version available** - for this version, yes

**Describe the bug**
cloth config window in mods menu crashes 1.18.2

go to mods menu and then click on roll combat then to the config button

**Expected behavior**
no crash

https://aofpaste.com/ogacibewey.yaml

**Comment by ZsoltMolnarrr** [comment]
I am unable to reproduce the issue.
Do you have paid version of Minecraft?
Did you try to replicate the issue with only Combat Roll installed on 1.18.2, to come to the conclusion that this mod is the source of the issue?

**Comment by Razatop** [comment]
Not OP here but also having this crash, can post crash report/ log if needed.

**Comment by ZsoltMolnarrr** [comment]
Please update your installation to use the latest version of all mods and the loader itself.
