### ISSUE TITLE
Reduce roll range in liquid.

### ISSUE THREAD

**Issue by HySand** [ZsoltMolnarrr/Rolling#19]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
Combat roll in water is odd.

**Describe the solution you'd like**
Reduce the roll range in water and lava to simulate resistance.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Thank you for the suggestion, I like the idea!
Roll range is somewhat reduced on ice, it would make perfect sense to implement this too.

**Comment by ZsoltMolnarrr** [comment]
Implemented in 1.3.0
