### ISSUE TITLE
crash minecraft 1.18.2 when entering world or server of mine

### ISSUE THREAD

**Issue by Wh1gg4** [ZsoltMolnarrr/Rolling#27]
**Minecraft version** - ? Minecraft 1.18.2
**Mod loader** - ? forge 40.2.9
**Mod version** - ? combat roll 1.1.5+1.18.2
**I am using the latest version available** - ? Yes

**Describe the bug**
after i uninstalled pufferfish skills mod ,quark ,quark,oddities, whenever i tried to create new world or join server minecraft just crash and not enough crash mod show that combat roll have identified as potential crash.

**To Reproduce**
1. install the mod i mention above
2. enter minecraft
3. join server or world i created

**Expected behavior**
working i guess

**Screenshots or video recordings**
![image](https://github.com/ZsoltMolnarrr/CombatRoll/assets/127105582/fc7fa2ba-e816-4d66-9e24-8131962467e4)

[crash-2023-08-11_15.29.52-client.txt](https://github.com/ZsoltMolnarrr/CombatRoll/files/12319808/crash-2023-08-11_15.29.52-client.txt)
![image](https://github.com/ZsoltMolnarrr/CombatRoll/assets/127105582/9c0909a5-583c-4b54-9df3-fd73b6d8be66)

**Additional context**
the combat roll mod working with no issue before i installed pufferfish skills mod ,quark ,quark,oddities.
i suspect pufferfish skills might have to with this and all the mod is up to date.

**Comment by ZsoltMolnarrr** [comment]
Your problem is likely caused by an unstable version of Forge mod loader, or an incompatible mod.
1.18.2 is no longer supported. You can use it as is.
