### ISSUE TITLE
Crash client with a CombatRoll

### ISSUE THREAD

**Issue by LeoDemitori** [ZsoltMolnarrr/Rolling#31]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric (letest)
**I am using the latest version available** - Yes

**Describe the bug**
Client crash when trying to start a roll animation

**Logs**
[combatroll_crash.txt](https://github.com/ZsoltMolnarrr/CombatRoll/files/13079073/combatroll_crash.txt)

**Comment by ZsoltMolnarrr** [comment]
Could you tell me which specific mod besides Combat Roll is needed to be installed to reproduce this issue?
I was never able to reproduce this.

**Comment by LeoDemitori** [comment]
> Could you tell me which specific mod besides Combat Roll is needed to be installed to reproduce this issue? I was never able to reproduce this.

- airhop: Air Hop 8.0.0
- better_climbing: Better Climbing 3
- + Crawl  (In fabrication mod feature)
- betteranimationscollection: Better Animations Collection 8.0.0
- bettercombat: Better Combat 1.7.4+1.20.1
- player-animator: Player Animator 1.0.2-rc1+1.20

**Other**
- carryon: Carry On 2.1.2.5
- cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal

**Optimizations**
- immediatelyfast: ImmediatelyFast 1.2.6+1.20.2
- indium: Indium 1.0.27+mc1.20.1
- lazydfu: LazyDFU 0.1.3
- sodium: Sodium 0.5.3
- lithium: Lithium 0.11.2
- vanillatweaks: VanillaTweaks 1.5.70 (maybe)
- carpet-extra: Carpet Extra 1.4.115
- carpet-fixes: Carpet Fixes 1.20-1.16.1

**Comment by ZsoltMolnarrr** [comment]
I am sorry, as mentioned I need the **specific singular** mod that is causing the problem, not a list of mods.
Unfortunately I don't have the development capacity to do the troubleshooting, so in cases like this, help is needed from the community.

**Comment by ZsoltMolnarrr** [comment]
Specifics are still wanted to resolve this issue.

**Comment by ZsoltMolnarrr** [comment]
This crash is only possible with an other mod mutating the functionset of `PacketByteBuf`.
Something related to core networks.
There is nothing I can do to fix it, because this breaks a foundational part of the communication layer.

Feel free to reopen if this happens without a mod that doesn't alter communication layer.
