### ISSUE TITLE
Add Fall Recovery (roll to reduce fall damage and nullify trip damage)

### ISSUE THREAD

**Issue by OPStellar** [ZsoltMolnarrr/Rolling#35]
**I read project readme, checked client side and server side configurations, and no such feature exists** - Kind of… I haven't used the mod because I don't need a *combat* roll, but I figured since this mod already adds a roll function, this feature could be implemented into the existing one instead of creating a new mod or expansion.

**Is your feature request related to a problem? Please describe.**
In the mod description, it mentions that `Roll ability can only be used when player is: not using item, not jumping, not swimming.`

**Describe the solution you'd like**
While I agree the combat roll should not be performed while jumping (to avoid aerial front-flips), perhaps it can be used on the descent, so it is only available to use mid-air when a player falls a certain distance (namely the distance that would cause damage) or when there is a certain range of space between the player and the ground beneath them when they begin their descent– whatever seems the most balanced.

**Describe alternatives you've considered**
I thought to look for parachutes, which could save a player in the event that they fall with it equipped, but I feel like that's much more planned ahead, whereas a combat roll is something practical that can be done with no equipment. The current vanilla alternative is placing water, which nullifies all fall damage and is a stupidly cheap trick, but I want something more practical: a maneuver, not a tool.

**Additional context**
In real life, it only helps reduce injury by only a small amount, dissipating the damage to not cause the whole body to absorb the impact. That said, I imagine this could nullify damage from 'trips' (gentle drops) in the game if timed properly.
Rolling into a cleaner landing should probably cause additional wear to all equipment worn.

**Comment by ZsoltMolnarrr** [comment]
This is not within the scope of this project sorry.
