### ISSUE TITLE
Server setting "allow_rolling_while_weapon_cooldown" not functional when used with Better Combat

### ISSUE THREAD

**Issue by tkaleita** [ZsoltMolnarrr/Rolling#36]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric
**Mod version** - 1.3.0
**I am using the latest version available** - ?

**Describe the bug**
The server config setting "allow_rolling_while_weapon_cooldown" has no effect (while used with Better Combat).
This was tested on the "Prominence II" Modpack.

**To Reproduce**
1. Install Prominence II Modpack on CurseForge.
2. Set "allow_rolling_while_weapon_cooldown" to true
3. Go ingame and attack with weapon
4. Try to roll during attack
5. Attack is not interrupted and roll is not performed

**Expected behavior**
I expected the attack to be interrupted with a roll.

**Additional context**
Sorry I couldnt test minimal working example
And also sorry if this is intended behaviour
But I would also really like to be able to cancel my attacks with the roll
It would make it feel really nice

**Comment by ZsoltMolnarrr** [comment]
During the windup phase, the weapon is not actually on cooldown, hence the feature works correctly.
