### ISSUE TITLE
Less than 3 blocks roll distance

### ISSUE THREAD

**Issue by redactedscribe** [ZsoltMolnarrr/Rolling#37]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I'd like to set roll distance to one less than the default.

**Describe the solution you'd like**
Ability to set the roll distance rather than additional roll distance.

**Describe alternatives you've considered**
Just use the default of 3.

Thanks!

**Comment by ZsoltMolnarrr** [comment]
The server config `additional_roll_distance` can be given a negative value, or default attribute value can be changed.
