### ISSUE TITLE
CombatRoll mod crashing upon launch.

### ISSUE THREAD

**Issue by Moxaco** [ZsoltMolnarrr/Rolling#38]
**Minecraft version** - 1.20.1
**Mod Loader** - Forge 47.2.19
**Mod Version** - 1.3.0
**I am using the latest version available** - Yes.

**Describe the bug**
(My english is not that good, so expect grammar fails)
I enter the launcher, with the mod on "mods" folder, and the game crashes on Minecraft loading screen, sending the error code 1.
This way i know the mods are the problem and not anything else.

I have tried:
- Putting every mod one by one to see which one is the problem to initiate. This way i discovered that 2 mods were the problem.
- Tried initiating without that mod. It launches successfully but, obviously, without the mod. Tried both empty folder and filled with mods i prepared and both worked.
- Launched with ONLY the mod, but the game crashed and sent me error code 1 again.

**To Reproduce**
Just initiate the game with the mod in, and it causes the error.

**Expected behavior**
I expected the launcher to, well, launch and play the modpack i made.

**Screenshots or video recordings**
No need.

**Additional context**
"Latest" filed in.
[latest.log](https://github.com/ZsoltMolnarrr/CombatRoll/files/13783839/latest.log)

If needed, i'll fill up with other files so the problem can be solved quickly.

**Comment by ZsoltMolnarrr** [comment]
[28dic2023 03:14:19.444] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'playeranimator', Requested by: 'combatroll', Expected range: '[1,)', Actual version: '[MISSING]'
	Mod ID: 'cloth_config', Requested by: 'combatroll', Expected range: '[11,)', Actual version: '[MISSING]'
