### ISSUE TITLE
allow_rolling_while_weapon_cooldown doesnt work

### ISSUE THREAD

**Issue by SweepySpud** [ZsoltMolnarrr/Rolling#39]
**Minecraft version** - 1.20.1
**Mod loader** - Forge
**Mod version** - 1.3.0
**I am using the latest version available** - Yep

**Describe the bug**
```    // Allows combat roll while the player has its weapon on cooldown
    "allow_rolling_while_weapon_cooldown": true,
```
This option in the config doesn't work. Even when I set this to true, I can't roll while my sword is on cooldown.

**To Reproduce**
1. set the allow_rolling_while_weapon_cooldown setting in the config file to true
2. go in minecraft and left click with a sword
3. attempt to roll on the weapon cooldown (it doesnt work)

**Expected behavior**
you roll whie you are on your weapon cooldown

**Screenshots or video recordings**
These are the mods im using
<img width="731" alt="Screenshot 2024-01-06 at 10 32 06" src="https://github.com/ZsoltMolnarrr/CombatRoll/assets/81664820/6e00a728-a9f5-4b1c-abe3-10d1824fda3a">
<img width="753" alt="Screenshot 2024-01-06 at 10 32 22" src="https://github.com/ZsoltMolnarrr/CombatRoll/assets/81664820/907428d5-cfd2-49e1-8387-e6b7be27f9d7">
**Additional context**

**Comment by ZsoltMolnarrr** [comment]
I am unable to reproduce this issue.
