### ISSUE TITLE
Forge Version Crashes Servers

### ISSUE THREAD

**Issue by AzureDoom** [ZsoltMolnarrr/Rolling#4]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - combatroll-forge-1.0.0+1.19.jar
**I am using the latest version available** - Yes

**Describe the bug**
Mod crashes on server to due to calling screen code in common.

**To Reproduce**

Add mod to server

**Expected behavior**
Server works lol

Log: https://gist.github.com/AzureDoom/c7ecfefb78b56ad10f8998c9c53964e7

**Comment by ZsoltMolnarrr** [comment]
Hey!
Thanks for reporting, I'll try to fix it!
