### ISSUE TITLE
bug with the hotkey

### ISSUE THREAD

**Issue by peow** [ZsoltMolnarrr/Rolling#40]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric 0.14.22
**Mod version** - 1.3.0+1.20.1
**I am using the latest version available** - yes

**Describe the bug**
if you type in the chat the letter that you put as hotkey for dash, for example "R", and quickly press Enter to send the message, the Dash may be used, and sometimes an even bigger bug occurs in which the Dash becomes happening nonstop

I made a video explaining it to make it easier to understand: 

https://www.youtube.com/watch?v=qOR_hAJL8iM

in this video i was only using Cloth Config, Fabric API, ModMenu, PlayerAnimator and Combatroll

log: 
[latest.log](https://github.com/ZsoltMolnarrr/CombatRoll/files/13848232/latest.log)

if you are going to fix this, please update to Fabric 1.20.1 and make it compatible with Fabric Loader 0.14.22 please, thank you

**Comment by ZsoltMolnarrr** [comment]
I've played several hours of SMP recently, and non of us have experienced such issue.
However, looking into the underlying code, I noticed Combat Roll handles the input in a non-standard way.

It would help a lot if you could test and give feedback about the potential solution I found.

Posted on Discord #combat-roll channel.

**Comment by peow** [comment]
i downloaded and tested and it still happens :(
you need to press enter a few milliseconds after pressing the hotkey

I also tested the mod on Forge 1.20.1 and was able to reproduce the issue

**Comment by ZsoltMolnarrr** [comment]
I don't know about any alternative solution then.
The published builds does handle the keybind in a standard way.

**Comment by peow** [comment]
what about disable the roll while the chat is active? then when you close the chat, the roll becomes active again 100ms later

**Comment by ZsoltMolnarrr** [comment]
I posted a new version, on Discord.
Could you test that one please too?

**Comment by peow** [comment]
the problem persist ;(, u can dm me if you want

**Comment by ZsoltMolnarrr** [comment]
Improvements to the keybind handling are added. Release processing now.
Any additional you have with keybind modifiers (Shift, Alt, etc...) are problems I cannot fix, because these are not supported by the game.
