### ISSUE TITLE
Add support for 1.20.4

### ISSUE THREAD

**Issue by EchoEllet** [ZsoltMolnarrr/Rolling#41]
It would be great to be able to use this mod in the latest version

**Comment by ZsoltMolnarrr** [comment]
The mod will be updated eventually. No need for this kind of ticket.

**Comment by EchoEllet** [comment]
> The mod will be updated eventually. No need for this kind of ticket.

No need for this kind of comment, too. It was just a question

**Comment by ZsoltMolnarrr** [comment]
No problem :) These kind of discussions typically go on our Discord.
