### ISSUE TITLE
Support for left-handed GUI

### ISSUE THREAD

**Issue by fotnite-vevo** [ZsoltMolnarrr/Rolling#42]
**I read project readme, checked client side and server side configurations, and no such feature exists**
Yes.

**Is your feature request related to a problem? Please describe.**
When I select "Main Hand: Left" from the skin customization menu, the roll indicator covers the offhand slot in the hotbar (which gets moved to the right side when this setting is selected)

**Describe the solution you'd like**
When "Main Hand: Left" is enabled, move the roll indicator to the right side of the hotbar, or move the indicator somewhere else on the screen that won't cover the offhand under either main hand settings

**Describe alternatives you've considered**
Add an option to disable the roll indicator

**Additional context**
What using Main Hand: Left looks like currently:
![Screenshot from 2024-02-03 09-05-37](https://github.com/ZsoltMolnarrr/CombatRoll/assets/68102115/44f0067a-e7f9-4897-b5d4-6ec361d4cac5)

**Comment by ZsoltMolnarrr** [comment]
Open mod settings (Mod Menu > Combat Roll > Settings > Move the arrow), drag the indicator whereever you want it.
