### ISSUE TITLE
Roll charges even when paused

### ISSUE THREAD

**Issue by Acat1234** [ZsoltMolnarrr/Rolling#45]
**Minecraft version** - 1.20.1
**Mod loader** - Forge
**Mod version** - 1.3.2
**I am using the latest version available** - Yes

**Describe the bug**
So if you use the roll and then pause (press Esc) it still fills back up even when paused
**To Reproduce**
Roll and pause it still charges

**Expected behavior**
The charge pauses too

**Screenshots or video recordings**
Idk how to screen record

**Additional context**
I dont have any

**Comment by ZsoltMolnarrr** [comment]
Thank you for raising the issue, I never noticed this before.

**Comment by Acat1234** [comment]
I'm glad to bring this to your attention
