### ISSUE TITLE
Allow Combat Rolling while on weapon cooldown does not work with Better Combat installed.

### ISSUE THREAD

**Issue by lostdoge08** [ZsoltMolnarrr/Rolling#47]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric
**Mod version** - 1.3.2+1.20.1
**I am using the latest version available** - Yes

**Describe the bug**
When the option to allow rolling during weapon cooldown is enabled, but Better Combat is installed, the function does not work properly. Any items that use the Better Combat attack system prevent Combat Roll from working during the attack animation, even if allowing during the weapon cooldown is enabled. The roll does work once the attack animation ends, even if the weapon cooldown hasn't. Rolling works during the upswing as well, however it breaks the attack animation.

**To Reproduce**
1. Go to the server config and set "allow_rolling_while_weapon_cooldown" to true.
2. Try to roll while attacking with a weapon using the Better Combat system.
3. To show that the config is still functional, attack with something that doesn't use the better combat system, like a pickaxe or shovel, and the roll should work.

**Expected behavior**
For the roll cancel out the attack animation (but not the weapon cooldown) and allow you to roll.

**Screenshots or video recordings**

https://github.com/ZsoltMolnarrr/CombatRoll/assets/146174915/87b273ae-f9c0-4f25-ae21-9b5b2f558849

**Comment by ZsoltMolnarrr** [comment]
Currently this config only works for vanilla attacks.

Not working with Better Combat swings is a feature, not a bug.
Animations would be conflicting if this was allowed.

Please make a specific technical recommendation, to make this actionable.

**Comment by lostdoge08** [comment]
Ah I see, alright then! Unfortunately the only thing I can recommend is to specify that the config option will not work with Better Combat attacks so nobody gets confused in the future. Thanks for the quick reply!
