### ISSUE TITLE
Conflicts with Better Combat and Cloth Config?

### ISSUE THREAD

**Issue by NovaViper** [ZsoltMolnarrr/Rolling#51]
**Minecraft version** - 1.21.1
**Mod loader** - NeoForge v21.1.21
**Mod version** - 2.0.0+1.21.1
**I am using the latest version available** - Yes

**Describe the bug**
If I load Better Combat v2.0.0+1.21.1 along with Combat Roll, the game crashes with ``Caused by: java.lang.module.ResolutionException: Module combat_roll contains package net.tinyconfig, module bettercombat exports package net.tinyconfig to combat_roll``; while I load the same mods with other mods (such as Guard Villagers v2.3.0), I get this error: `Modules combat_roll and bettercombat export package net.tinyconfig to module guardvillagers`.

**To Reproduce**
1. Download Combat Roll and Better Combat along with their dependencies
2. Launch the game
3. Game immediately crashes

**Expected behavior**
The mods should just load up without crashing the game

**Screenshots or video recordings**

**Additional context**
Logs with just Better Combat, Combat Roll, and Cloth Config: https://mclo.gs/lSpeFls
Logs with BC, CR, CC, and Guard Villagers: https://mclo.gs/V5pGpFk

**Comment by ZsoltMolnarrr** [comment]
Thank you for the report.

A fix was publish in v2.0.1 of both mods. Please report back if the issue persist after updating.

**Comment by NovaViper** [comment]
The update fixed it! Thank you for the speedy reply and patch!
