### ISSUE TITLE
Roll after short press and release the run key

### ISSUE THREAD

**Issue by Kenqr** [ZsoltMolnarrr/Rolling#52]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I want to use the same key for both rolling and running, like many other games do.

**Describe the solution you'd like**
Add an option to use the run key for rolling. Press and release to roll, press and hold to run.

**Describe alternatives you've considered**
Add an option to trigger rolling after a short press and release. In this case, users can use any key (e.g. crouch key) for rolling, not just the run key.

**Additional context**
Many games (Souls-like, Warframe, etc.) use the same key for running and rolling.
Some advantages of using the same key for running and rolling:
- One less key to remember.
- Frees up a key slot that other mods can use.
- More intuitive for players familiar with these games.

Disadvantage:
- Slightly less responsive, since you'll be rolling on key release, not key press.

**Comment by ZsoltMolnarrr** [comment]
I am sad to say, Minecraft Vanilla key binding system simply does not allow this. :(
