### ISSUE TITLE
Roll UI stays on screen when F1 is clicked

### ISSUE THREAD

**Issue by Tralty** [ZsoltMolnarrr/Rolling#53]
**Minecraft version** - 1.21.1
**Mod loader** - NeoForge-21.1.72
**Mod version** - 2.0.1
**I am using the latest version available** - Yes

**Describe the bug**
When I click F1, the UI for rolling stays on the screen.

**To Reproduce**
1. Click F1 in a random world

**Expected behavior**
The UI for rolling should still be on the screen when F1 is clicked, tested on my modpack, then before creating this bug report, I made sure to test it on a different instance.

**Screenshots or video recordings**
![2024-10-22_07 08 28](https://github.com/user-attachments/assets/38e0da11-eb3f-43a5-bf96-e15275f4f7e4)

**Comment by ZsoltMolnarrr** [comment]
Thank you for the notice, will be fixed in the next update!
