### ISSUE TITLE
Roll Icon displays improperly on HUD (displays too low and centered)

### ISSUE THREAD

**Issue by ekd403** [ZsoltMolnarrr/Rolling#54]
**Minecraft version** - 1.20.1
**Mod loader** - Forge
**Mod version** - 1.3.3
**I am using the latest version available** - Yes, most recent 1.20.1 version

**Describe the bug**
roll icon displays too low and also centered on the HUD, whereas it should display off to the side (as seen in functioning fabric counterpart)

**Comment by ZsoltMolnarrr** [comment]
The roll icon can be relocated in the mod config.
There is even a UI for that, where you can drag it :)
